# Generated by Django 3.0.3 on 2020-07-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staffaccount',
            table='crm_account',
        ),
    ]
