# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-06 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_account', '0002_auto_20200804_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffaccount',
            name='role_type',
            field=models.CharField(choices=[('crm', '客户管理系统'), ('customer', '客户端'), ('controller', '中台管控端'), ('agent', '代理商管理系统')], max_length=24, verbose_name='角色'),
        ),
    ]
