# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-19 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('agent_customer_id', models.IntegerField(default=0, verbose_name='客户id')),
                ('agent_id', models.IntegerField(verbose_name='代理商id')),
                ('person_id', models.IntegerField(default=0, verbose_name='用户id')),
                ('company_id', models.IntegerField(default=0, verbose_name='公司id')),
                ('order_item_id', models.IntegerField(default=0, verbose_name='订单商品详情id')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('phone', models.CharField(default='', max_length=16, verbose_name='联系电话')),
                ('email', models.TextField(default='', max_length=32, verbose_name='emali')),
                ('identification', models.CharField(default='', max_length=24, verbose_name='身份证号')),
                ('autograph', models.TextField(default='', verbose_name='签名URL')),
                ('url', models.TextField(default='[]', verbose_name='合同url')),
                ('img_url', models.TextField(default='[]', verbose_name='合同图片')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'agent_order_contract',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('agent_customer_id', models.IntegerField(default=0, verbose_name='代理商客户id')),
                ('mg_order_id', models.IntegerField(verbose_name='订单id')),
                ('agent_id', models.IntegerField(default=0, verbose_name='代理商id')),
                ('person_id', models.IntegerField(default=0, verbose_name='用户id')),
                ('company_id', models.IntegerField(default=0, verbose_name='公司id')),
                ('source', models.CharField(choices=[('app', 'app'), ('crm', 'crm'), ('other', 'other')], default='other', max_length=64, verbose_name='订单来源')),
                ('number', models.CharField(default='', max_length=24, verbose_name='订单编号')),
                ('status', models.CharField(choices=[('order_launched', '待支付'), ('payment_finished', '待发货'), ('delivery_finished', '已发货'), ('order_closed', '已取消'), ('order_finished', '已完成')], default='order_launched', max_length=24, verbose_name='订单状态')),
                ('last_payment_time', models.DateTimeField(default=None, null=True, verbose_name='最后支付时间')),
                ('name', models.CharField(default='', max_length=16, verbose_name='姓名')),
                ('phone', models.CharField(default='', max_length=24, verbose_name='手机号')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'agent_order_base',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('goods_id', models.IntegerField(verbose_name='商品id')),
                ('merchandise_snapshoot_id', models.IntegerField(verbose_name='商品快照id')),
                ('school_name', models.CharField(default='', max_length=32, verbose_name='学校名称')),
                ('school_city', models.CharField(default='', max_length=32, verbose_name='学校城市')),
                ('major_name', models.CharField(default='', max_length=64, verbose_name='专业名称')),
                ('category', models.CharField(choices=[('undergraduate', '专升本'), ('specialty', '高起专'), ('graduate', '考研'), ('qualification', '资格证'), ('other', '其它')], default='other', max_length=64, verbose_name='类别')),
                ('duration', models.CharField(choices=[('one_year', '1年'), ('one_half_year', '1.5年'), ('two_year', '2年'), ('two_half_year', '2.5年'), ('other', '其它')], default='other', max_length=32, verbose_name='时长')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent_order.Order')),
            ],
            options={
                'db_table': 'agent_order_orderitem',
            },
        ),
    ]
