# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-21 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='number',
            field=models.CharField(default='', max_length=64, verbose_name='合同编号'),
        ),
    ]
