# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-26 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_order', '0002_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='email',
            field=models.CharField(default='', max_length=128, verbose_name='emali'),
        ),
    ]
