# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-19 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0003_orderitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='contract',
            name='agent_customer_id',
            field=models.IntegerField(default=0, verbose_name='客户id'),
        ),
        migrations.AddField(
            model_name='contract',
            name='company_id',
            field=models.IntegerField(default=0, verbose_name='公司id'),
        ),
        migrations.AddField(
            model_name='contract',
            name='person_id',
            field=models.IntegerField(default=0, verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='order',
            name='agent_customer_id',
            field=models.IntegerField(default=0, verbose_name='代理商客户id'),
        ),
        migrations.AddField(
            model_name='order',
            name='company_id',
            field=models.IntegerField(default=0, verbose_name='公司id'),
        ),
        migrations.AddField(
            model_name='order',
            name='person_id',
            field=models.IntegerField(default=0, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='order_item_id',
            field=models.IntegerField(default=0, verbose_name='订单商品详情id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='agent_id',
            field=models.IntegerField(default=0, verbose_name='代理商id'),
        ),
    ]
