# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-03 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_order', '0004_auto_20200902_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='send_email_number',
            field=models.IntegerField(default=0, verbose_name='发送邮件次数'),
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('wait_send', '待发送'), ('wait_signed', '待签署'), ('signed', '已签署')], default='wait_send', max_length=64, verbose_name='合同状态'),
        ),
    ]
