# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-03 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_order', '0005_auto_20200903_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_services',
            field=models.CharField(choices=[('full_payment', '全额支付'), ('installment', '分期支付')], default='full_payment', max_length=128, verbose_name='订单支付服务'),
        ),
    ]
