# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-04 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_order', '0006_order_pay_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deposit',
            field=models.IntegerField(default=0, verbose_name='首付款'),
        ),
    ]
