# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-07 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agent_order', '0007_order_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('number', models.CharField(default='', max_length=24, verbose_name='回款单号')),
                ('payment_record_id', models.IntegerField(default=0, verbose_name='订单支付单id')),
                ('staff_id', models.IntegerField(default=0, verbose_name='员工id')),
                ('plan_time', models.DateTimeField(null=True, verbose_name='计划回款时间')),
                ('plan_amount', models.IntegerField(default=0, verbose_name='计划回款金额')),
                ('status', models.CharField(choices=[('wait_pay', '欠缴费'), ('paying', '回款中'), ('paid', '已回款')], default='wait_pay', max_length=64, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent_order.Order')),
            ],
            options={
                'db_table': 'agent_order_plan',
            },
        ),
    ]
