# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-14 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_order', '0009_orderitem_template_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='template_id',
            field=models.IntegerField(default=0, verbose_name='合同模板id'),
        ),
    ]
