# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-14 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_order', '0010_contract_template_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='content',
            field=models.TextField(default='[]', verbose_name='合同参数'),
        ),
    ]
