# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-10-15 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agent_order', '0011_contract_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('person_id', models.IntegerField(verbose_name='用户id')),
                ('goods_id', models.IntegerField(verbose_name='商品id')),
                ('tags', models.TextField(default='[]', verbose_name='评价标签')),
                ('content', models.TextField(default='', verbose_name='评价内容')),
                ('pics', models.TextField(default='[]', verbose_name='评价图片')),
                ('videos', models.TextField(default='[]', verbose_name='评价视频')),
                ('server_attitude', models.IntegerField(default=0, verbose_name='服务态度')),
                ('course_quality', models.IntegerField(default=0, verbose_name='课程质量')),
                ('major', models.IntegerField(default=0, verbose_name='院校专业')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'agent_order_evaluation',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='evaluation',
            field=models.CharField(choices=[('wait_evaluation', '待评价'), ('evaluated', '已评价')], default='wait_evaluation', max_length=32, verbose_name='评价状态'),
        ),
        migrations.AddField(
            model_name='orderitemevaluation',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent_order.OrderItem', verbose_name='订单物品id'),
        ),
    ]
