# Generated by Django 3.0.3 on 2020-07-15 22:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('number', models.CharField(max_length=48, verbose_name='交易编号')),
                ('amount', models.IntegerField(verbose_name='金额，有正负之分, 单位：分')),
                ('remark', models.TextField(default='', verbose_name='记录备注')),
                ('pay_type', models.CharField(choices=[('bank', '银行'), ('alipay', '支付宝'), ('wechat', '微信'), ('balance', '余额')], max_length=12, verbose_name='支付方式')),
                ('business_type', models.CharField(choices=[('order', '订单'), ('balance', '余额')], max_length=16, verbose_name='业务来源')),
                ('business_id', models.IntegerField(null=True, verbose_name='业务ID')),
                ('own_type', models.CharField(choices=[('company', '公司'), ('person', '个人')], max_length=16, verbose_name='拥有者类型')),
                ('own_id', models.IntegerField(verbose_name='拥有者ID')),
                ('trader_type', models.CharField(choices=[('company', '公司'), ('person', '个人')], max_length=16, verbose_name='交易者类型')),
                ('trader_id', models.IntegerField(null=True, verbose_name='交易者ID')),
                ('input_record_id', models.IntegerField(null=True, verbose_name='入账单ID')),
                ('output_record_id', models.IntegerField(null=True, verbose_name='出账单ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'moddleground_transaction_record',
            },
        ),
        migrations.CreateModel(
            name='TransactionOutputRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('number', models.CharField(max_length=48, verbose_name='交易编号')),
                ('amount', models.IntegerField(verbose_name='金额，有正负之分, 单位：分')),
                ('remark', models.TextField(default='', verbose_name='记录备注')),
                ('pay_type', models.CharField(choices=[('bank', '银行'), ('alipay', '支付宝'), ('wechat', '微信'), ('balance', '余额')], max_length=12, verbose_name='支付方式')),
                ('business_type', models.CharField(choices=[('order', '订单'), ('balance', '余额')], max_length=16, verbose_name='业务来源')),
                ('business_id', models.IntegerField(null=True, verbose_name='业务ID')),
                ('own_type', models.CharField(choices=[('company', '公司'), ('person', '个人')], max_length=16, verbose_name='拥有者类型')),
                ('own_id', models.IntegerField(verbose_name='拥有者ID')),
                ('trader_type', models.CharField(choices=[('company', '公司'), ('person', '个人')], max_length=16, verbose_name='交易者类型')),
                ('trader_id', models.IntegerField(null=True, verbose_name='交易者ID')),
                ('status', models.CharField(choices=[('pay_finish', '付款成功'), ('transaction_dealing', '交易处理中'), ('account_finish', '到账成功')], default='pay_finish', max_length=24, verbose_name='交易状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.TransactionRecord')),
            ],
            options={
                'db_table': 'moddleground_transaction_output_record',
            },
        ),
        migrations.CreateModel(
            name='TransactionInputRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('number', models.CharField(max_length=48, verbose_name='交易编号')),
                ('amount', models.IntegerField(verbose_name='金额，有正负之分, 单位：分')),
                ('remark', models.TextField(default='', verbose_name='记录备注')),
                ('pay_type', models.CharField(choices=[('bank', '银行'), ('alipay', '支付宝'), ('wechat', '微信'), ('balance', '余额')], max_length=12, verbose_name='支付方式')),
                ('business_type', models.CharField(choices=[('order', '订单'), ('balance', '余额')], max_length=16, verbose_name='业务来源')),
                ('business_id', models.IntegerField(null=True, verbose_name='业务ID')),
                ('own_type', models.CharField(choices=[('company', '公司'), ('person', '个人')], max_length=16, verbose_name='拥有者类型')),
                ('own_id', models.IntegerField(verbose_name='拥有者ID')),
                ('trader_type', models.CharField(choices=[('company', '公司'), ('person', '个人')], max_length=16, verbose_name='交易者类型')),
                ('trader_id', models.IntegerField(null=True, verbose_name='交易者ID')),
                ('status', models.CharField(choices=[('pay_finish', '付款成功'), ('transaction_dealing', '交易处理中'), ('account_finish', '到账成功')], default='pay_finish', max_length=24, verbose_name='交易状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.TransactionRecord')),
            ],
            options={
                'db_table': 'moddleground_transaction_input_record',
            },
        ),
    ]
