# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-11 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioninputrecord',
            name='status',
            field=models.CharField(choices=[('pay_request', '付款请求'), ('pay_finish', '付款成功'), ('transaction_dealing', '交易处理中'), ('account_finish', '到账成功'), ('account_fail', '交易失败')], default='pay_finish', max_length=24, verbose_name='交易状态'),
        ),
        migrations.AlterField(
            model_name='transactionoutputrecord',
            name='status',
            field=models.CharField(choices=[('pay_request', '付款请求'), ('pay_finish', '付款成功'), ('transaction_dealing', '交易处理中'), ('account_finish', '到账成功'), ('account_fail', '交易失败')], default='pay_finish', max_length=24, verbose_name='交易状态'),
        ),
    ]
