# Generated by Django 3.0.3 on 2020-09-11 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionoutputrecord',
            name='related_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_transaction', to='transaction.TransactionRecord'),
        ),
        migrations.AlterField(
            model_name='transactioninputrecord',
            name='status',
            field=models.CharField(choices=[('pay_request', '付款请求'), ('pay_finish', '付款成功'), ('account_finish', '到账成功'), ('account_fail', '交易失败')], default='pay_request', max_length=24, verbose_name='交易状态'),
        ),
        migrations.AlterField(
            model_name='transactionoutputrecord',
            name='status',
            field=models.CharField(choices=[('pay_request', '付款请求'), ('pay_finish', '付款成功'), ('account_finish', '到账成功'), ('account_fail', '交易失败')], default='pay_request', max_length=24, verbose_name='交易状态'),
        ),
        migrations.AlterField(
            model_name='transactionoutputrecord',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='transaction.TransactionRecord'),
        ),
    ]
