# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-14 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20200911_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioninputrecord',
            name='order_number',
            field=models.CharField(default='', max_length=256, verbose_name='第三方交易编号'),
        ),
        migrations.AddField(
            model_name='transactioninputrecord',
            name='related_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_related_transaction', to='transaction.TransactionRecord'),
        ),
        migrations.AddField(
            model_name='transactionoutputrecord',
            name='order_number',
            field=models.CharField(default='', max_length=256, verbose_name='第三方交易编号'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='order_number',
            field=models.CharField(default='', max_length=256, verbose_name='第三方交易编号'),
        ),
        migrations.AlterField(
            model_name='transactioninputrecord',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_transaction', to='transaction.TransactionRecord'),
        ),
        migrations.AlterField(
            model_name='transactionoutputrecord',
            name='related_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_related_transaction', to='transaction.TransactionRecord'),
        ),
        migrations.AlterField(
            model_name='transactionoutputrecord',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_transaction', to='transaction.TransactionRecord'),
        ),
    ]
