# Generated by Django 3.0.3 on 2020-09-11 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20200911_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioninputrecord',
            name='related_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_related_transaction', to='transaction.TransactionRecord'),
        ),
        migrations.AlterField(
            model_name='transactioninputrecord',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_transaction', to='transaction.TransactionRecord'),
        ),
        migrations.AlterField(
            model_name='transactionoutputrecord',
            name='related_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_related_transaction', to='transaction.TransactionRecord'),
        ),
        migrations.AlterField(
            model_name='transactionoutputrecord',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_transaction', to='transaction.TransactionRecord'),
        ),
    ]
