# Generated by Django 3.0.3 on 2020-09-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20200911_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioninputrecord',
            name='order_number',
            field=models.CharField(default='', max_length=256, verbose_name='第三方交易编号'),
        ),
        migrations.AddField(
            model_name='transactionoutputrecord',
            name='order_number',
            field=models.CharField(default='', max_length=256, verbose_name='第三方交易编号'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='order_number',
            field=models.CharField(default='', max_length=256, verbose_name='第三方交易编号'),
        ),
    ]
