# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-17 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('thumbnail', models.TextField(verbose_name='缩略图')),
                ('name', models.CharField(max_length=256, verbose_name='广告名称')),
                ('url', models.TextField(default='', verbose_name='跳转地址')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'crm_adsense_advertisement',
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('label', models.CharField(max_length=128, verbose_name='标签')),
                ('name', models.CharField(max_length=256, verbose_name='广告位名称')),
                ('width', models.IntegerField(verbose_name='宽度')),
                ('height', models.IntegerField(verbose_name='高度')),
                ('is_enable', models.BooleanField(default=False, verbose_name='是否使用')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'crm_adsense_space',
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_adsense.Space'),
        ),
    ]
