# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-17 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_adsense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_enable',
            field=models.BooleanField(default=False, verbose_name='是否使用'),
        ),
    ]
