# Generated by Django 3.0.3 on 2020-08-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandisesnapshoot',
            name='brand_name',
            field=models.CharField(default='', max_length=256, verbose_name='品牌名称'),
        ),
        migrations.AddField(
            model_name='merchandisesnapshoot',
            name='production_name',
            field=models.CharField(default='', max_length=256, verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='merchandisesnapshoot',
            name='remark',
            field=models.TextField(verbose_name='快照备注,包含规格属性'),
        ),
        migrations.AlterField(
            model_name='merchandisesnapshoot',
            name='specification_id',
            field=models.IntegerField(verbose_name='商品规格ID'),
        ),
    ]
