# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-04 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200804_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('pay_finish', '付款成功'), ('transaction_dealing', '交易处理中'), ('account_finish', '到账成功'), ('account_fail', '交易失败')], default=None, max_length=16, null=True, verbose_name='交易状态'),
        ),
    ]
