# Generated by Django 3.0.3 on 2020-08-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_paymentrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('pay_finish', '付款成功'), ('transaction_dealing', '交易处理中'), ('account_finish', '到账成功'), ('account_fail', '交易失败')], default=None, max_length=64, null=True, verbose_name='交易状态'),
        ),
    ]
