# Generated by Django 3.0.3 on 2020-08-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200804_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandisesnapshoot',
            name='despatch_type',
            field=models.CharField(choices=[('logistics', '物流交付'), ('phone_top_up', '手机充值'), ('eduction_contract', '教育合同')], default='eduction_contract', max_length=64, verbose_name='商品发货方式'),
            preserve_default=False,
        ),
    ]
