# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-10 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_merchandisesnapshoot_despatch_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order_launched', '待支付'), ('payment_finished', '待发货'), ('delivery_finished', '已发货'), ('order_closed', '已取消'), ('order_finished', '已完成')], default='order_launched', max_length=24, verbose_name='订单状态'),
        ),
    ]
