# Generated by Django 3.0.3 on 2020-07-15 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enterprise',
            unique_together={('license_number',)},
        ),
    ]
