# Generated by Django 3.0.3 on 2020-07-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_auto_20200715_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='remark',
            field=models.TextField(default='', verbose_name='备注'),
            preserve_default=False,
        ),
    ]
