# Generated by Django 3.0.3 on 2020-07-15 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBalanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('number', models.CharField(max_length=48, verbose_name='交易编号')),
                ('amount', models.IntegerField(verbose_name='金额，有正负之分，单位：分')),
                ('pay_type', models.CharField(choices=[('bank', '银行'), ('alipay', '支付宝'), ('wechat', '微信'), ('balance', '余额')], max_length=12, verbose_name='支付方式')),
                ('remark', models.TextField(default='', verbose_name='记录备注')),
                ('input_record_id', models.IntegerField(null=True, verbose_name='入账凭证id')),
                ('output_record_id', models.IntegerField(null=True, verbose_name='出账凭证id')),
                ('customer_id', models.IntegerField(verbose_name='客户id')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'customer_finance_balance',
            },
        ),
    ]
