# Generated by Django 3.0.3 on 2020-07-13 21:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('contacts', models.CharField(max_length=64, verbose_name='联系人')),
                ('gender', models.CharField(choices=[('man', '男士'), ('woman', '女士'), ('unknown', '未知')], default='unknown', max_length=24, verbose_name='性别')),
                ('phone', models.CharField(max_length=64, verbose_name='联系电话')),
                ('city', models.CharField(max_length=64, verbose_name='城市')),
                ('address', models.CharField(max_length=256, verbose_name='详细地址')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'moddleground_user_adddress',
            },
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('bank_name', models.CharField(max_length=24, verbose_name='银行名称')),
                ('bank_code', models.CharField(max_length=20, verbose_name='银行编码')),
                ('bank_number', models.CharField(max_length=64, verbose_name='银行卡号')),
                ('name', models.CharField(max_length=16, verbose_name='开户人姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='开户人手机号')),
                ('identification', models.CharField(max_length=24, verbose_name='开户人身份证')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'moddleground_user_bankcard',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('identification', models.CharField(max_length=24, verbose_name='身份证号')),
                ('id_front', models.CharField(default='', max_length=256, verbose_name='身份证正面')),
                ('id_back', models.CharField(default='', max_length=256, verbose_name='身份证反面')),
                ('id_in_hand', models.CharField(default='', max_length=256, verbose_name='身份证反面')),
                ('remark', models.TextField(default='', null=True, verbose_name='备注')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'moddleground_user_certification',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('education', models.CharField(choices=[('primary', '小学'), ('middle', '初中'), ('high', '高中'), ('undergraduate', '本科'), ('college', '大专'), ('middlecollege', '中专'), ('master', '硕士'), ('doctor', '博士'), ('other', '其他')], default='other', max_length=24, verbose_name='学历')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'moddleground_user_education',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('man', '男士'), ('woman', '女士'), ('unknown', '未知')], default='unknown', max_length=24, verbose_name='性别')),
                ('birthday', models.DateField(null=True, verbose_name='生日')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='手机号')),
                ('email', models.CharField(default='', max_length=128, verbose_name='邮箱')),
                ('wechat', models.CharField(default='', max_length=128, verbose_name='微信')),
                ('qq', models.CharField(default='', max_length=128, verbose_name='qq')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'moddleground_user_base',
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('certification', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.Certification')),
                ('default_address', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.Address')),
                ('default_bankcard', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.BankCard')),
                ('last_education', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.Education')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'moddleground_user_status',
            },
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'moddleground_user_statistics',
            },
        ),
        migrations.CreateModel(
            name='UserBeavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'moddleground_user_behavior',
            },
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='certification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='bankcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
