# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-06 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('company_id', models.IntegerField(verbose_name='公司id')),
                ('name', models.CharField(default='', max_length=32, verbose_name='公司名称')),
                ('province', models.CharField(default='', max_length=32, verbose_name='省')),
                ('city', models.CharField(default='', max_length=32, verbose_name='市')),
                ('area', models.CharField(default='', max_length=32, verbose_name='区')),
                ('address', models.CharField(default='', max_length=128, verbose_name='详细地址')),
                ('official_seal', models.CharField(default='', max_length=256, verbose_name='公章')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'crm_agent_base',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('contacts', models.CharField(default='', max_length=32, verbose_name='联系人')),
                ('phone', models.CharField(default='', max_length=16, verbose_name='联系电话')),
                ('email', models.TextField(default='', max_length=32, verbose_name='emali')),
                ('gender', models.CharField(choices=[('man', '男士'), ('woman', '女士'), ('unknown', '未知')], default='unknown', max_length=24, verbose_name='性别')),
                ('account', models.CharField(default='', max_length=32, verbose_name='账号')),
                ('account_status', models.CharField(choices=[('enable', '启用'), ('notactive', '待激活'), ('lock', '锁定'), ('disable', '禁用')], default='notactive', max_length=24, verbose_name='账号状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_agent.Agent')),
            ],
            options={
                'db_table': 'crm_agent_contacts',
            },
        ),
    ]
