# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-05 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='公司名称'),
        ),
    ]
