# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-07 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='official_seal',
            field=models.TextField(default='', verbose_name='公章'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.CharField(default='', max_length=64, verbose_name='emali'),
        ),
    ]
