# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-11 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_agent', '0002_auto_20200807_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='account_status',
        ),
    ]
