# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-12 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_agent', '0003_remove_contacts_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='appkey',
            field=models.CharField(default='', max_length=128, verbose_name='appkey'),
        ),
    ]
