# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-07-23 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('template_id', models.CharField(max_length=64, verbose_name='模板id')),
                ('template_label', models.CharField(max_length=64, verbose_name='模板标签')),
                ('param', models.TextField(verbose_name='参数')),
                ('content', models.TextField(verbose_name='内容')),
                ('label', models.CharField(max_length=64, verbose_name='短信平台标签')),
                ('unique_no', models.CharField(max_length=128, verbose_name='唯一标识')),
                ('scene', models.CharField(choices=[('register', '注册验证码')], max_length=64, verbose_name='场景标识')),
                ('source_type', models.CharField(choices=[('crm', 'crm'), ('customer', '客户端')], max_length=64, verbose_name='接收短信的用户来源平台')),
                ('status', models.CharField(choices=[('success', '成功'), ('fail', '失败'), ('resend', '已重发')], max_length=32, verbose_name='发送状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'crm_tool_smsrecord',
            },
        ),
    ]
