# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-07-29 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_tool', '0002_auto_20200729_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsrecord',
            name='scene',
            field=models.CharField(choices=[('register', '注册验证码'), ('forget', '找回密码验证码'), ('bindcard', '绑定银行卡'), ('login', '登陆')], max_length=64, verbose_name='场景标识'),
        ),
    ]
