# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-20 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm_tool', '0003_auto_20200729_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('type_desc', models.CharField(max_length=64, verbose_name='类别描述')),
                ('type', models.CharField(max_length=64, verbose_name='类别')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('key', models.CharField(max_length=64, verbose_name='key')),
                ('value', models.TextField(default='', verbose_name='value')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'crm_tool_config',
            },
        ),
    ]
