# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-24 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm_tool', '0006_auto_20200902_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('title', models.CharField(default='', max_length=64, verbose_name='标题')),
                ('content', models.TextField(default='', max_length=64, verbose_name='内容')),
                ('classify', models.CharField(choices=[('notify', '通知'), ('announcement', '公告')], max_length=32, verbose_name='类别：通知/公告')),
                ('platform', models.CharField(choices=[('crm', 'crm'), ('crm_app', 'crm小程序'), ('agent', '代理商'), ('customer_wechat', '微信小程序'), ('customer', '客户端')], max_length=64, verbose_name='通知（公告）来源平台')),
                ('status', models.CharField(choices=[('disable', '禁用'), ('enable', '启用')], max_length=32, verbose_name='通知（公告）状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'crm_tool_notice',
            },
        ),
    ]
