# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-24 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_tool', '0007_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='classify',
            field=models.CharField(choices=[('notify', '通知'), ('announcement', '公告')], default='notify', max_length=32, verbose_name='类别：通知/公告'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='platform',
            field=models.CharField(choices=[('crm', 'crm'), ('agent', '代理商'), ('customer_wechat', '微信小程序'), ('customer', '客户端')], default='crm', max_length=64, verbose_name='通知（公告）来源平台'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('disable', '禁用'), ('enable', '启用')], default='enable', max_length=32, verbose_name='通知（公告）状态'),
        ),
    ]
