# Generated by Django 3.0.3 on 2020-07-30 20:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('name', models.CharField(max_length=24, verbose_name='品牌名称')),
                ('industry', models.CharField(choices=[('eduction', '教育'), ('e-commerce', '电商')], max_length=24, verbose_name='行业')),
                ('description', models.CharField(max_length=256, verbose_name='品牌描述')),
                ('company_id', models.IntegerField(verbose_name='公司ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'middleground_production_brand',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('name', models.CharField(max_length=24, verbose_name='产品名称')),
                ('description', models.CharField(max_length=256, verbose_name='品牌描述')),
                ('attribute_list', models.TextField(verbose_name='属性json')),
                ('workflow_list', models.TextField(verbose_name='流程json')),
                ('company_id', models.IntegerField(verbose_name='公司ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Brand')),
            ],
            options={
                'db_table': 'middleground_production_production',
            },
        ),
    ]
