# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-06 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='agent_id',
            field=models.IntegerField(default=0, verbose_name='代理商id'),
        ),
    ]
