# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-17 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_staff', '0003_auto_20200806_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.CharField(default='', max_length=256, verbose_name='家庭住址'),
        ),
        migrations.AddField(
            model_name='staff',
            name='bank_number',
            field=models.CharField(default='', max_length=32, verbose_name='银行卡号'),
        ),
        migrations.AddField(
            model_name='staff',
            name='diploma_img',
            field=models.TextField(default='[]', verbose_name='毕业证书'),
        ),
        migrations.AddField(
            model_name='staff',
            name='education',
            field=models.CharField(choices=[('primary', '小学'), ('middle', '初中'), ('high', '高中'), ('undergraduate', '本科'), ('college', '大专'), ('middlecollege', '中专'), ('master', '硕士'), ('doctor', '博士'), ('other', '其他')], default='other', max_length=24, verbose_name='学历'),
        ),
        migrations.AddField(
            model_name='staff',
            name='emergency_contact',
            field=models.CharField(default='', max_length=64, verbose_name='紧急联系人'),
        ),
        migrations.AddField(
            model_name='staff',
            name='emergency_phone',
            field=models.CharField(default='', max_length=20, verbose_name='紧急联系人电话'),
        ),
        migrations.AddField(
            model_name='staff',
            name='entry_time',
            field=models.DateField(blank=True, null=True, verbose_name='入职时间'),
        ),
        migrations.AddField(
            model_name='staff',
            name='identification',
            field=models.CharField(default='', max_length=64, verbose_name='身份证号'),
        ),
    ]
