# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-17 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_staff', '0004_auto_20200817_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='contract',
            field=models.CharField(default='', max_length=128, verbose_name='合同编号'),
        ),
    ]
