# Generated by Django 3.0.3 on 2020-09-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller_staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='permission_key',
            field=models.CharField(default='', max_length=256, verbose_name='权限appkey'),
        ),
    ]
