# Generated by Django 3.0.3 on 2020-09-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller_staff', '0002_auto_20200812_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='permission_id',
            field=models.IntegerField(default=0, verbose_name='权限id'),
            preserve_default=False,
        ),
    ]
