# Generated by Django 3.0.3 on 2020-09-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller_staff', '0003_staff_permission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='permission_id',
            field=models.IntegerField(default=None, null=True, verbose_name='权限id'),
        ),
    ]
