# Generated by Django 3.0.3 on 2020-07-15 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('username', models.CharField(max_length=64, verbose_name='账号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('last_login_time', models.DateTimeField(null=True, verbose_name='最后一次登录时间')),
                ('last_login_ip', models.CharField(default='', max_length=64, verbose_name='最后登录ip')),
                ('register_ip', models.CharField(default='', max_length=64, verbose_name='注册IP')),
                ('status', models.CharField(choices=[('enable', '启用'), ('notactive', '待激活'), ('lock', '锁定'), ('disable', '禁用')], default='notactive', max_length=64, verbose_name='账号状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('customer_id', models.IntegerField(verbose_name='客户id')),
            ],
            options={
                'db_table': 'customer_personal_account',
            },
        ),
    ]
