# Generated by Django 3.0.3 on 2020-07-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customeraccount',
            table='customer_account_base',
        ),
    ]
