# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-26 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_account', '0004_auto_20200812_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tripartite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('category', models.CharField(max_length=64, verbose_name='分类')),
                ('openid', models.CharField(default='', max_length=128, verbose_name='openid')),
                ('customer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_account.CustomerAccount')),
            ],
            options={
                'db_table': 'customer_account_tripartite',
            },
        ),
    ]
