# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-24 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_account', '0005_tripartite'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='last_login_phone_system',
            field=models.CharField(choices=[('ios', 'ios'), ('android', '安卓'), ('other', '其它')], default='other', max_length=32, verbose_name='最后一次登陆手机系统'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='last_login_phone_unique',
            field=models.CharField(default='', max_length=128, verbose_name='最后一次登陆设备编码'),
        ),
    ]
