# coding=UTF-8

import datetime
from support.common.maker import BaseLoader


class RelationsLoader(BaseLoader):

    def generate(self):
        return [
                {
                    'school_name': '湖北大学',
                    'major_name': '电子信息工程',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '会计',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '国际经济与贸易',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '市场营销',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '电子商务',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '物流管理',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '导游',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '酒店管理',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '广告设计与制作',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '传播与策划',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '旅游英语',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '法学',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '教育学',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '计算机科学与技术',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '工程管理',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '工商管理',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '会计学',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '人力资源管理',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '行政管理',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '经济学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '金融学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '国际经济与贸易',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '法学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '教育学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '汉语言文学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '传播学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '心理学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '电子信息工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '计算机科学与技术',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '物联网工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '环境工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '药学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '信息管理与信息系统',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '工程管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '工商管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '市场营销',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '会计学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '人力资源管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '公共事业管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '行政管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '旅游管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '视觉传达设计',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '环境设计',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北大学',
                    'major_name': '化学工程与工艺',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '英语',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '艺术设计',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '生物科技',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '统计学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '机械设计制造及自动化',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '电气工程及其自动化',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '电子信息工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '通信工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '计算机科学与技术',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '软件工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '数字传媒技术',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '建筑学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '土木工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '环境工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '化工工艺',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '制药工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '交通工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '生物工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '农业机械化及其自动化',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '国际经济与贸易',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '金融学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '信息管理与信息系统',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '工程管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '人力资源管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '市场营销',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '会计学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '财务管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '电子商务',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '行政管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '学前教育',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '道路桥梁工程技术',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '建筑工程技术',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '建筑工程管理',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '模具设计与制造',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '机电一体化技术',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '电气自动化技术',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '通信技术',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '会计',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '会计电算化',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '市场营销',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '电子商务',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '旅游管理',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北工业大学',
                    'major_name': '艺术设计',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '汉语言文学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '英语',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '广播电视新闻学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '历史学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '化学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '数学与应用数学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '计算机科学与技术',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '通讯工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '物理学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '土木工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '经济学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '会计学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '财务管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '生物科学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '行政管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '思想政治教育',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '法学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '教育学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '工商管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '旅游管理',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '思想政治教育',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '行政管理',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '学前教育',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '语文教育',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '应用英语',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '数学教育',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '计算机科学与技术',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '教育管理',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '历史教育',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '会计',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '艺术设计',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '市场营销',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '经济管理',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '应用电子技术',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '电气自动化技术',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '导游',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '工商管理',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '湖北师范大学',
                    'major_name': '土木工程',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '电子商务',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '工商企业管理',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '公共事务管理',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '广告设计与制作',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '会计',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '建筑工程管理',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '酒店管理',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '粮油储藏与检测技术',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '旅游管理',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '市场营销',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '文秘',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '物流管理',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '学前教育',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '汉语言文学',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '环境检测与治理技术',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '电子信息工程技术',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '计算机应用技术',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '机电一体化技术',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '通信技术',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '艺术设计',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '汉语言文学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '新闻学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '英语',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '广告学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '美术学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '艺术设计',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '电子信息工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '化学工程与工艺',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '环境工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '计算机科学与技术',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '粮食工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '软件工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '应用化学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '工程管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '行政管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '会计学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '金融学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '经济学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '旅游管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '人力资源管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '市场营销',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '法学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '教育学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉工程大学',
                    'major_name': '学前教育',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '学前教育',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '工程管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '工商管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '国际经济与贸易',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '会计学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '市场营销',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '安全工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '材料成型及控制工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '采矿工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '车辆工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '电子信息工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '机械设计制造及自动化',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '计算机科学与技术',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '金属材料工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '汽车服务工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '土木工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '无机非金属材料工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '物流工程',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '冶金工程',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '自动化',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '药学',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '法学',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '电子商务',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '工程造价',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '国际经济与贸易',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '护理',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '会计电算化',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '汽车运用技术',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '市场营销',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '文秘',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '物流管理',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '商务英语',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '电脑艺术设计',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '装饰艺术设计',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '电气自动化技术',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '机电一体化技术',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '计算机应用技术',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '建筑工程管理',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '临床医学',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '冶金技术',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '应用化工技术',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '安全工程',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '材料成型及控制工程',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '采矿工程',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '车辆工程',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '电子信息工程',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '机械设计制造及自动化',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '计算机科学与技术',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '金属材料工程',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '汽车服务工程',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '土木工程',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉科技大学',
                    'major_name': '无机非金属材料工程',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '武汉理工大学',
                    'major_name': '工程管理',
                    'category':'undergraduate' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '建筑工程技术',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '计算机应用技术',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '护理',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '会计',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '学前教育',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '英语',
                    'category':'specialty' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '经济学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '园林',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '视觉传达设计',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '法学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '教育学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '农村经济管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '物流管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '医学检验技术',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '学前教育',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '英语',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '医学影像技术',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '生物工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '电子信息工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '汉语言文学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '农学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '园艺',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '应用化学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '美术学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '机械设计制造及自动化',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '农业资源与环境',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '电气工程及其自动化',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '动物医学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '计算机科学与技术',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '动物药学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '物联网工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '水产养殖学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '土木工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '财务管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '石油工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '公共事务管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '食品质量与安全',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '音乐学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '植物保护',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '人力资源管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '动物科学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '国际经济与贸易',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '广播电视编导',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '社会工作',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '临床医学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '思想政治教育',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '中西医临床学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '体育教育',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '护理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '广播电视学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '工程管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '数学与应用数学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '工商管理',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '物理学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '化学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '市场营销',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '风景园林',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '会计学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '地质学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '金融学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '环境设计',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '生物技术',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '应用心理学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '给排水科学工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '工业设计',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '水文与水源工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '网络工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '化学工程与工艺',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '勘察技术与工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '环境工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '油气存储工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '建筑学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '海洋油气工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '城乡规划',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '食品科学与工程',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '金融学',
                    'category':'undergraduate' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '经济学',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '法学',
                    'category':'highcost' ,
                    'duration':'two_half_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '教育学',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '学前教育',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '汉语言文学',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '英语',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '应用化学',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '机械设计制造及自动化',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '电气工程及其自动化',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '电子信息工程',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '计算机科学与技术',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '物联网工程',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '土木工程',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '石油工程',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '食品质量与安全',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '植物保护',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '动物科学',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '园林',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '临床医学',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '中西医临床学',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '医学检验技术',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '医学影像技术',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '护理',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '工程管理',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '工商管理',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '市场营销',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '会计学',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '人力资源管理',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '农林经济管理',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '物流管理',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '视觉传达设计',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '长江大学',
                    'major_name': '环境设计',
                    'category':'highcost' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '中南财经政法大学',
                    'major_name': '投资学',
                    'category':'undergraduate' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '中南财经政法大学',
                    'major_name': '会计学',
                    'category':'undergraduate' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '中国地质大学',
                    'major_name': '地质工程',
                    'category':'undergraduate' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '中国地质大学',
                    'major_name': '治安学',
                    'category':'undergraduate' ,
                    'duration':'five_year',
                },
                {
                    'school_name': '中国地质大学',
                    'major_name': '会计学',
                    'category':'undergraduate' ,
                    'duration':'five_year',
                }

        ]
