# Generated by Django 3.0.3 on 2020-07-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='show_image',
            field=models.CharField(max_length=256, verbose_name='展示图片'),
        ),
    ]
