# Generated by Django 3.0.3 on 2020-07-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_auto_20200724_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='despatch_type',
            field=models.CharField(choices=[('logistics', '物流交付'), ('phone_top_up', '手机充值'), ('eduction_contract', '教育合同')], max_length=64, verbose_name='发货方式'),
        ),
    ]
