# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-11 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='img_url',
            field=models.TextField(default='[]', verbose_name='合同图片'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_payment_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='最后支付时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=16, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(default='', max_length=24, verbose_name='订单编号'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=24, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order_launched', '待支付'), ('payment_finished', '待发货'), ('delivery_finished', '已发货'), ('order_closed', '已取消'), ('order_finished', '已完成')], default='order_launched', max_length=24, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='autograph',
            field=models.TextField(default='', verbose_name='签名URL'),
        ),
    ]
