# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-19 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0002_auto_20200811_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='category',
            field=models.CharField(choices=[('undergraduate', '专升本'), ('specialty', '高起专'), ('graduate', '考研'), ('qualification', '资格证'), ('other', '其它')], default='other', max_length=64, verbose_name='类别'),
        ),
    ]
