# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-07-31 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('mg_order_id', models.CharField(max_length=32, verbose_name='订单id')),
                ('source', models.CharField(choices=[('app', 'app'), ('crm', 'crm'), ('other', 'other')], default='other', max_length=64, verbose_name='订单来源')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'crm_order_order',
            },
        ),
    ]
