# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-07-31 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('customer_id', models.IntegerField(verbose_name='客户id')),
                ('mg_order_id', models.IntegerField(verbose_name='订单id')),
                ('source', models.CharField(choices=[('app', 'app'), ('crm', 'crm'), ('other', 'other')], default='other', max_length=64, verbose_name='订单来源')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'crm_order_order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('goods_id', models.IntegerField(verbose_name='商品id')),
                ('merchandise_snapshoot_id', models.IntegerField(verbose_name='商品快照id')),
                ('school_name', models.CharField(default='', max_length=32, verbose_name='学校名称')),
                ('major_name', models.CharField(default='', max_length=64, verbose_name='专业名称')),
                ('duration', models.CharField(choices=[('one_year', '1年'), ('one_half_year', '1.5年'), ('two_year', '2年'), ('two_half_year', '2.5年'), ('other', '其它')], default='other', max_length=32, verbose_name='时长')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_order.Order')),
            ],
            options={
                'db_table': 'crm_order_orderitem',
            },
        ),
    ]
