# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-03 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='school_city',
            field=models.CharField(default='', max_length=32, verbose_name='学校城市'),
        ),
    ]
