# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-06 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_order', '0002_orderitem_school_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agent_id',
            field=models.IntegerField(null=True, verbose_name='代理商id'),
        ),
    ]
