# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-07-29 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('name', models.CharField(max_length=32, verbose_name='专业名称')),
                ('content', models.TextField(verbose_name='专业描述')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'crm_tool_major',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('name', models.CharField(max_length=32, verbose_name='学校名称')),
                ('logo_url', models.CharField(default='', max_length=256, verbose_name='学校url')),
                ('content', models.TextField(verbose_name='学校描述')),
                ('province', models.CharField(max_length=16, verbose_name='学校所在省')),
                ('city', models.CharField(max_length=16, verbose_name='学校所在市')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'crm_tool_school',
            },
        ),
    ]
