# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-13 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm_university', '0002_major_icons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('category', models.CharField(choices=[('undergraduate', '专升本'), ('specialty', '高起专'), ('graduate', '考研'), ('qualification', '资格证'), ('other', '其它')], default='other', max_length=64, verbose_name='类别')),
                ('duration', models.CharField(choices=[('one_year', '1年'), ('one_half_year', '1.5年'), ('two_year', '2年'), ('two_half_year', '2.5年'), ('other', '其它')], default='other', max_length=32, verbose_name='时长')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_university.Major')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_university.School')),
            ],
            options={
                'db_table': 'crm_university_relations',
            },
        ),
    ]
