# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-13 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_university', '0003_relations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relations',
            name='category',
        ),
        migrations.RemoveField(
            model_name='relations',
            name='duration',
        ),
        migrations.AddField(
            model_name='relations',
            name='content',
            field=models.TextField(default='', verbose_name='描述'),
        ),
    ]
