# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-24 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_university', '0005_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='years',
            name='category',
            field=models.CharField(choices=[('undergraduate', '专升本'), ('specialty', '高起专'), ('highcost', '高起本'), ('graduate', '考研'), ('qualification', '资格证'), ('other', '其它')], default='other', max_length=64, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='years',
            name='duration',
            field=models.CharField(choices=[('one_year', '1年'), ('one_half_year', '1.5年'), ('two_year', '2年'), ('two_half_year', '2.5年'), ('five_year', '5年'), ('other', '其它')], default='other', max_length=32, verbose_name='时长'),
        ),
    ]
