# Generated by Django 3.0.3 on 2020-09-17 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('username', models.CharField(max_length=64, verbose_name='账号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('nick', models.CharField(default='', max_length=32, verbose_name='昵称')),
                ('head_url', models.CharField(default='', max_length=256, verbose_name='头像URL')),
                ('last_login_time', models.DateTimeField(null=True, verbose_name='最后一次登录时间')),
                ('last_login_ip', models.CharField(default='', max_length=64, verbose_name='最后登录ip')),
                ('register_ip', models.CharField(default='', max_length=64, verbose_name='注册IP')),
                ('status', models.CharField(choices=[('enable', '启用'), ('notactive', '待激活'), ('lock', '锁定'), ('disable', '禁用')], default='notactive', max_length=64, verbose_name='账号状态')),
                ('role_type', models.CharField(choices=[('crm', '客户管理系统'), ('customer', '客户端'), ('controller', '中台管控端'), ('agent', '代理商管理系统')], max_length=24, verbose_name='角色')),
                ('role_id', models.IntegerField(verbose_name='角色id')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'controller_account_base',
            },
        ),
    ]
