# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-20 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent_event', '0002_remove_trackevent_person_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trackevent',
            table='agent_event_track',
        ),
    ]
