# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-17 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agent_event', '0002_stafforderevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('staff_id', models.IntegerField(default=0, verbose_name='员工id')),
                ('organization_id', models.IntegerField(verbose_name='组织id')),
                ('remark', models.TextField(default='', null=True, verbose_name='备注')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('agent_id', models.IntegerField(verbose_name='代理商id')),
                ('agent_customer_id', models.IntegerField(default=0, verbose_name='代理商客户id')),
                ('describe', models.TextField(verbose_name='描述')),
                ('type', models.CharField(choices=[('visit', '添加访问记录'), ('intention', '意向修改'), ('customer', '客户信息修改'), ('other', '其它')], default='other', max_length=64, verbose_name='跟中类型')),
            ],
            options={
                'db_table': 'agent_event_operation',
            },
        ),
        migrations.DeleteModel(
            name='TrackEvent',
        ),
    ]
