# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-20 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_event', '0002_remove_trackevent_person_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackevent',
            name='agent_staff_id',
        ),
        migrations.AddField(
            model_name='trackevent',
            name='staff_id',
            field=models.IntegerField(default=0, verbose_name='员工id'),
        ),
    ]
