# Generated by Django 3.0.3 on 2020-07-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='head_url',
            field=models.CharField(default='', max_length=256, verbose_name='头像URL'),
        ),
    ]
