# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-18 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_personal', '0002_auto_20200716_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('goods_id', models.IntegerField(default=0, verbose_name='用户id')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_personal.Customer')),
            ],
            options={
                'db_table': 'customer_personal_collection_record',
            },
        ),
    ]
