# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-24 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_personal', '0005_customermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermessage',
            name='status',
            field=models.CharField(choices=[('read', '已读'), ('unread', '未读')], default='unread', max_length=32, verbose_name='消息状态'),
        ),
    ]
