# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-27 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_personal', '0006_auto_20200924_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermessage',
            name='customer',
        ),
        migrations.DeleteModel(
            name='CustomerMessage',
        ),
    ]
