# Generated by Django 3.0.3 on 2020-06-29 12:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑编码')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('man', '男士'), ('woman', '女士'), ('unknown', '未知')], default='unknown', max_length=24, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('education', models.CharField(choices=[('primary', '小学'), ('middle', '初中'), ('high', '高中'), ('undergraduate', '本科'), ('college', '大专'), ('middlecollege', '中专'), ('master', '硕士'), ('doctor', '博士'), ('other', '其他')], default='other', max_length=24, verbose_name='学历')),
                ('phone', models.CharField(default='', max_length=20, null=True, verbose_name='手机号')),
                ('email', models.CharField(default='', max_length=128, null=True, verbose_name='邮箱')),
                ('wechat', models.CharField(default='', max_length=128, null=True, verbose_name='微信')),
                ('qq', models.CharField(default='', max_length=128, null=True, verbose_name='qq')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'customer_info',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑编码')),
                ('name', models.CharField(default='', max_length=64, verbose_name='部门名称')),
                ('parent_id', models.IntegerField(default=0, verbose_name='对应上级部门id')),
                ('describe', models.TextField(default='', verbose_name='描述')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'staff_department',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑编码')),
                ('active_uid', models.IntegerField(default=0, verbose_name='主动方uid')),
                ('active_name', models.CharField(max_length=128, verbose_name='主动方姓名')),
                ('active_type', models.CharField(choices=[('staff', '员工'), ('user', '用户'), ('system', '系统')], default='system', max_length=64, verbose_name='主动方类型')),
                ('passive_uid', models.IntegerField(default=0, verbose_name='被动方uid')),
                ('passive_name', models.CharField(max_length=128, verbose_name='被动方姓名')),
                ('passive_type', models.CharField(choices=[('staff', '员工'), ('user', '用户'), ('system', '系统')], default='system', max_length=64, verbose_name='被动方类型')),
                ('journal_type', models.CharField(choices=[('login', '登录'), ('other', '其它'), ('status reset', '导入数据状态重置'), ('delete', '删除'), ('look', '查詢'), ('edit', '編輯'), ('search', '搜索'), ('remove', '刪除'), ('update', '更新'), ('add', '新增'), ('import', '数据导入'), ('recover', '恢复'), ('allot', '分配'), ('close', '关闭')], default='other', max_length=64, verbose_name='日志类型')),
                ('record_detail', models.TextField(verbose_name='详情')),
                ('remark', models.TextField(verbose_name='备注')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'staff_journal',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑编码')),
                ('name', models.CharField(default='', max_length=64, verbose_name='角色名称')),
                ('describe', models.TextField(default='', verbose_name='描述')),
                ('parent_id', models.IntegerField(default=0, verbose_name='对应上级角色id')),
                ('rules', models.TextField(default='[]', verbose_name='角色对应权限')),
                ('data_level', models.CharField(choices=[('only_self', '仅自己可见数据'), ('self_and_subordinate', '自己及下属'), ('all', '所有')], max_length=24, verbose_name='数据展现级别')),
                ('data_security', models.BooleanField(default=True, verbose_name='数据级别')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'staff_role',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑编码')),
                ('id_number', models.CharField(max_length=128, verbose_name='员工工号')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('man', '男士'), ('woman', '女士'), ('unknown', '未知')], default='unknown', max_length=24, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('education', models.CharField(choices=[('primary', '小学'), ('middle', '初中'), ('high', '高中'), ('undergraduate', '本科'), ('college', '大专'), ('middlecollege', '中专'), ('master', '硕士'), ('doctor', '博士'), ('other', '其他')], default='other', max_length=24, verbose_name='学历')),
                ('phone', models.CharField(default='', max_length=20, null=True, verbose_name='手机号')),
                ('email', models.CharField(default='', max_length=128, null=True, verbose_name='邮箱')),
                ('entry_time', models.DateField(blank=True, null=True, verbose_name='入职时间')),
                ('resignation_time', models.DateField(blank=True, null=True, verbose_name='离职时间')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否是管理员')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'staff_info',
            },
        ),
        migrations.CreateModel(
            name='TaskContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑编码')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='任务容器名称')),
                ('exec_parms', models.TextField(default='', verbose_name='执行参数')),
                ('group_list', models.TextField(default='', verbose_name='执行任务项')),
                ('status', models.CharField(choices=[('init', '初始化'), ('executting', '任务执行中'), ('finished', '任务执行完成'), ('failed', '任务失败'), ('suspending', '任务暂停中'), ('suspend', '任务暂停'), ('canceling', '任务取消中'), ('cancel', '任务取消')], default='init', max_length=128, verbose_name='任务执行状态')),
                ('type', models.CharField(choices=[('always', '一直执行'), ('time', '时间段内执行'), ('interval', '间隔时间执行'), ('once', '执行一次')], default='always', max_length=128, verbose_name='任务容器类型')),
                ('reason', models.TextField(default='', verbose_name='任务失败原因')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'task_container',
            },
        ),
        migrations.CreateModel(
            name='UserCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑编码')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('identification', models.CharField(max_length=24, verbose_name='身份证号')),
                ('id_front', models.CharField(default='', max_length=256, null=True, verbose_name='身份证正面')),
                ('id_back', models.CharField(default='', max_length=256, null=True, verbose_name='身份证反面')),
                ('id_in_hand', models.CharField(default='', max_length=256, null=True, verbose_name='身份证反面')),
                ('remark', models.TextField(default='', null=True, verbose_name='备注')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'user_certification',
            },
        ),
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑编码')),
                ('lable', models.CharField(default='', max_length=128, verbose_name='任务组标示')),
                ('name', models.CharField(default='', max_length=64, verbose_name='任务组名称')),
                ('exec_cls', models.CharField(default='', max_length=128, verbose_name='任务组执行类')),
                ('exec_parms', models.TextField(default='', verbose_name='任务组执行参数')),
                ('status', models.CharField(choices=[('init', '初始化'), ('generatting', '任务生成中'), ('generated', '任务生成完成'), ('executting', '任务执行中'), ('suspend', '任务暂停'), ('finished', '任务执行完成'), ('cancel', '任务取消')], default='init', max_length=32, verbose_name='任务组整体执行状态')),
                ('type', models.CharField(choices=[('always', '一直执行'), ('time', '时间段内执行'), ('interval', '间隔时间执行'), ('once', '执行一次')], default='always', max_length=128, verbose_name='任务组类型')),
                ('reason', models.TextField(default='', verbose_name='任务取消原因')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.TaskContainer')),
            ],
            options={
                'db_table': 'task_group',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑编码')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='任务名称')),
                ('exec_parms', models.TextField(default='', verbose_name='执行参数')),
                ('status', models.CharField(choices=[('init', '初始化'), ('executting', '任务执行中'), ('finished', '任务执行完成'), ('failed', '任务失败'), ('cancel', '任务取消')], default='init', max_length=32, verbose_name='任务执行状态')),
                ('reason', models.TextField(default='', verbose_name='任务失败原因')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.TaskGroup')),
            ],
            options={
                'db_table': 'task_info',
            },
        ),
        migrations.CreateModel(
            name='StaffAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑编码')),
                ('username', models.CharField(max_length=64, verbose_name='账号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='最后一次登录时间')),
                ('last_login_ip', models.CharField(default='', max_length=64, verbose_name='最后一次登录ip')),
                ('register_ip', models.CharField(default='', max_length=64, verbose_name='注册IP')),
                ('status', models.CharField(choices=[('enable', '启用'), ('notactive', '待激活'), ('lock', '锁定'), ('disable', '禁用')], default='notactive', max_length=64, verbose_name='账号状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Staff')),
            ],
            options={
                'db_table': 'staff_account',
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='certification',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='model.UserCertification'),
        ),
        migrations.CreateModel(
            name='DepartmentRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑编码')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Department')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Role')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Staff')),
            ],
            options={
                'db_table': 'staff_department_role',
            },
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑编码')),
                ('username', models.CharField(max_length=64, verbose_name='账号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='最后一次登录时间')),
                ('last_login_ip', models.CharField(default='', max_length=64, verbose_name='最后一次登录ip')),
                ('register_ip', models.CharField(default='', max_length=64, verbose_name='注册IP')),
                ('status', models.CharField(choices=[('enable', '启用'), ('notactive', '待激活'), ('lock', '锁定'), ('disable', '禁用')], default='notactive', max_length=64, verbose_name='账号状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('nick', models.CharField(max_length=64, verbose_name='昵称')),
                ('profile', models.CharField(max_length=256, verbose_name='头像')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Customer')),
            ],
            options={
                'db_table': 'customer_account',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='certification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='model.UserCertification'),
        ),
    ]
