# Generated by Django 3.0.3 on 2020-05-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='journal',
            table='staff_journal',
        ),
    ]
