# Generated by Django 3.0.3 on 2020-06-30 19:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBankCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑编码')),
                ('number', models.CharField(max_length=64, verbose_name='银行卡号')),
                ('name', models.CharField(max_length=16, verbose_name='开户人姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='开户人手机号')),
                ('identification', models.CharField(max_length=24, verbose_name='开户人身份证')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Customer')),
            ],
            options={
                'db_table': 'customer_bankcard',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑编码')),
                ('contacts', models.CharField(max_length=64, verbose_name='联系人')),
                ('gender', models.CharField(choices=[('man', '男士'), ('woman', '女士'), ('unknown', '未知')], default='unknown', max_length=24, verbose_name='性别')),
                ('phone', models.CharField(max_length=64, verbose_name='联系电话')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('city', models.CharField(max_length=64, verbose_name='城市')),
                ('address', models.CharField(max_length=256, verbose_name='详细地址')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Customer')),
            ],
            options={
                'db_table': 'customer_address',
            },
        ),
    ]
