# Generated by Django 3.0.3 on 2020-06-30 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_customeraddress_customerbankcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='certification',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='model.UserCertification'),
        ),
    ]
