# Generated by Django 3.0.3 on 2020-05-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20200519_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercertification',
            name='address',
        ),
        migrations.RemoveField(
            model_name='usercertification',
            name='city',
        ),
        migrations.AlterModelTable(
            name='departmentrole',
            table='staff_department_role',
        ),
    ]
