# Generated by Django 3.0.3 on 2020-07-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_auto_20200705_2248'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer_info_1',
        ),
        migrations.AlterModelTable(
            name='customeraccount',
            table='customer_account_1',
        ),
    ]
