# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-06 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('school_id', models.IntegerField(verbose_name='学校id')),
                ('major_id', models.IntegerField(verbose_name='专业id')),
                ('agent_id', models.IntegerField(null=True, verbose_name='代理商id')),
                ('merchandise_id', models.IntegerField(verbose_name='通用商品id')),
                ('duration', models.CharField(choices=[('one_year', '1年'), ('one_half_year', '1.5年'), ('two_year', '2年'), ('two_half_year', '2.5年'), ('other', '其它')], default='other', max_length=32, verbose_name='时长')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'agent_goods_base',
            },
        ),
    ]
