# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-13 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_goods', '0002_goods_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='category',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='merchandise_id',
        ),
        migrations.AddField(
            model_name='goods',
            name='relations_id',
            field=models.IntegerField(default=0, verbose_name='学校专业id'),
        ),
        migrations.AddField(
            model_name='goods',
            name='years_id',
            field=models.IntegerField(default=0, verbose_name='学年id'),
        ),
    ]
