# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-13 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_goods', '0003_auto_20200813_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='merchandise_id',
            field=models.IntegerField(default=0, verbose_name='通用商品id'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='relations_id',
            field=models.IntegerField(verbose_name='学校专业id'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='years_id',
            field=models.IntegerField(verbose_name='学年id'),
        ),
    ]
