# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-20 17:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agent_goods', '0006_poster_posterspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='posterspecification',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='posterspecification',
            name='update_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2020, 8, 20, 17, 56, 35, 604516), verbose_name='更新时间'),
            preserve_default=False,
        ),
    ]
