# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-21 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_goods', '0007_auto_20200820_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='staff_id',
            field=models.IntegerField(default=0, verbose_name='员工id'),
        ),
    ]
