# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-03 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_goods', '0008_poster_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='deposit',
            field=models.IntegerField(default=0, verbose_name='首付款'),
        ),
        migrations.AddField(
            model_name='poster',
            name='pay_services',
            field=models.CharField(choices=[('full_payment', '全额支付'), ('installment', '分期支付')], default='full_payment', max_length=128, verbose_name='订单支付服务'),
        ),
    ]
