# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-03 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_goods', '0009_auto_20200903_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='pay_plan',
            field=models.TextField(default='[]', verbose_name='剩余款项汇款计划'),
        ),
    ]
