# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-04 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_goods', '0010_poster_pay_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='posterspecification',
            name='original_price',
            field=models.IntegerField(default=0, verbose_name='原价'),
        ),
    ]
