# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-27 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agent_goods', '0012_goods_template_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('staff_id', models.IntegerField(default=0, verbose_name='审核人id')),
                ('status', models.CharField(choices=[('wait_post', '待提交'), ('wait_review', '待审核'), ('pass', '审核通过'), ('rejection', '审核拒绝')], default='wait_post', max_length=64, verbose_name='审核状态')),
                ('remark', models.TextField(default='', verbose_name='审核备注')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent_goods.Goods')),
            ],
            options={
                'db_table': 'agent_goods_review',
            },
        ),
    ]
