# Generated by Django 3.0.3 on 2020-07-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_staff', '0003_auto_20200716_1508'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staff',
            table='crm_staff_base',
        ),
    ]
