# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-06 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_staff', '0004_auto_20200716_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='手机号'),
        ),
    ]
