# Generated by Django 3.0.3 on 2020-07-30 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('sender_name', models.CharField(max_length=32, verbose_name='发送人')),
                ('sender_phone', models.CharField(max_length=32, verbose_name='发送人电话')),
                ('sender_address', models.CharField(max_length=32, verbose_name='发送地址')),
                ('receiver_name', models.CharField(max_length=32, verbose_name='收件人')),
                ('receiver_phone', models.CharField(max_length=32, verbose_name='收件人电话')),
                ('receiver_address', models.CharField(max_length=32, verbose_name='收件人地址')),
                ('status', models.CharField(choices=[('prepare', '待发货'), ('in_transit', '运输中'), ('delivery', '交付完成'), ('lost', '货物丢失'), ('return', '货品返回')], default='prepare', max_length=32, verbose_name='物流状态')),
                ('transit_company', models.CharField(choices=[('shunfeng', '顺风'), ('yunda', '韵达'), ('zhongtong', '中通'), ('debang', '德邦')], max_length=24, verbose_name='物流公司')),
                ('transit_number', models.CharField(default='', max_length=128, verbose_name='物流订单号')),
                ('remark', models.TextField(verbose_name='备注')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'middleground_logistics_base',
                'unique_together': {('transit_company', 'transit_number')},
            },
        ),
    ]
