# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-09 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('agent_id', models.IntegerField(default=0, verbose_name='代理商id')),
                ('name', models.CharField(default='', max_length=64, verbose_name='合同名称')),
                ('pdf_url', models.CharField(default='', max_length=256, verbose_name='合同模板pdf链接')),
                ('background_img_url', models.TextField(default='[]', verbose_name='合同背景图片')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('wait', '待审核'), ('adopt', '通过'), ('refuse', '拒绝')], default='draft', max_length=32, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'agent_contract_template',
            },
        ),
        migrations.CreateModel(
            name='TemplateParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('param_id', models.IntegerField(default=0, verbose_name='参数id')),
                ('page_number', models.IntegerField(default=0, verbose_name='页码')),
                ('coordinate_x', models.CharField(default='0', max_length=64, verbose_name='参数位置x坐标')),
                ('coordinate_y', models.CharField(default='0', max_length=64, verbose_name='参数位置y坐标')),
                ('length', models.CharField(default='0', max_length=64, verbose_name='参数宽度')),
                ('width', models.CharField(default='0', max_length=64, verbose_name='参数长度')),
                ('content', models.TextField(verbose_name='参数冗余配置')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent_contract.Template')),
            ],
            options={
                'db_table': 'agent_contract_template_param',
            },
        ),
    ]
