# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-10 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_contract', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateparam',
            name='length',
        ),
        migrations.AddField(
            model_name='templateparam',
            name='height',
            field=models.CharField(default='0', max_length=64, verbose_name='参数长度'),
        ),
        migrations.AlterField(
            model_name='templateparam',
            name='width',
            field=models.CharField(default='0', max_length=64, verbose_name='参数宽度'),
        ),
    ]
