# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-11 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_contract', '0002_auto_20200910_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateparam',
            name='coordinate_x',
            field=models.IntegerField(default='0', verbose_name='参数位置x坐标'),
        ),
        migrations.AlterField(
            model_name='templateparam',
            name='coordinate_y',
            field=models.IntegerField(default='0', verbose_name='参数位置y坐标'),
        ),
        migrations.AlterField(
            model_name='templateparam',
            name='height',
            field=models.IntegerField(default='0', verbose_name='参数高度'),
        ),
        migrations.AlterField(
            model_name='templateparam',
            name='width',
            field=models.IntegerField(default='0', verbose_name='参数宽度'),
        ),
    ]
