# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-02 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='position_id_list',
            field=models.TextField(default='[]', verbose_name='身份列表'),
        ),
    ]
