# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-09 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('name', models.CharField(max_length=64, verbose_name='参数名称')),
                ('name_key', models.CharField(max_length=64, verbose_name='参数key值')),
                ('key_type', models.CharField(choices=[('image', '图片'), ('text', '文本'), ('other', '其它')], default='other', max_length=64, verbose_name='参数类型')),
                ('default_value', models.CharField(max_length=64, verbose_name='默认值')),
                ('actual_value_source', models.CharField(choices=[('invoice', '发货单'), ('agent', '代理商'), ('other', '其它')], default='other', max_length=64, verbose_name='实际值来源对象')),
                ('actual_value_key', models.CharField(max_length=64, verbose_name='实际值来源对象参数')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'crm_contract_param',
            },
        ),
    ]
