# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-10 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='param',
            name='default_value',
            field=models.CharField(max_length=256, verbose_name='默认值'),
        ),
    ]
