# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-11 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_contract', '0002_auto_20200910_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='param',
            name='actual_value_key',
        ),
        migrations.AddField(
            model_name='param',
            name='is_allowed',
            field=models.BooleanField(default=True, verbose_name='是否允许修改'),
        ),
        migrations.AlterField(
            model_name='param',
            name='actual_value_source',
            field=models.CharField(choices=[('company', '企业填写'), ('customer', '客户填写'), ('system', '系统生成')], default='company', max_length=64, verbose_name='实际值来源对象'),
        ),
    ]
