# coding=UTF-8


from support.common.maker import BaseLoader


class RuleLoader(BaseLoader):

    def generate(self):
        return [
            {
                'name': '授权管理',
                'parent': "",
                'platform_name': "中台",
                'description': "授权管理",
                'remark': "",
            },
            {
                'name': '权限授权',
                'parent': "授权管理",
                'platform_name': "中台",
                'description': "权限授权",
                'remark': "",
            },
            {
                'name': '查询',
                'parent': "权限授权",
                'platform_name': "中台",
                'description': "查询",
                'remark': "",
            },
            {
                'name': '修改',
                'parent': "权限授权",
                'platform_name': "中台",
                'description': "修改",
                'remark': "",
            },
            {
                'name': '添加',
                'parent': "权限授权",
                'platform_name': "中台",
                'description': "添加",
                'remark': "",
            },
            {
                'name': '删除',
                'parent': "权限授权",
                'platform_name': "中台",
                'description': "删除",
                'remark': "",
            },
            {
                'name': '权限管理',
                'parent': "",
                'platform_name': "中台",
                'description': "权限管理",
                'remark': "",
            },
            {
                'name': '权限组管理',
                'parent': "权限管理",
                'platform_name': "中台",
                'description': "权限组管理",
                'remark': "",
            },
            {
                'name': '查询',
                'parent': "权限组管理",
                'platform_name': "中台",
                'description': "查询",
                'remark': "",
            },
            {
                'name': '修改',
                'parent': "权限组管理",
                'platform_name': "中台",
                'description': "修改",
                'remark': "",
            },
            {
                'name': '添加',
                'parent': "权限组管理",
                'platform_name': "中台",
                'description': "添加",
                'remark': "",
            },
            {
                'name': '删除',
                'parent': "权限组管理",
                'platform_name': "中台",
                'description': "删除",
                'remark': "",
            },
            {
                'name': '职位管理',
                'parent': "权限管理",
                'platform_name': "中台",
                'description': "职位管理",
                'remark': "",
            },
            {
                'name': '查询',
                'parent': "职位管理",
                'platform_name': "中台",
                'description': "查询",
                'remark': "",
            },
            {
                'name': '修改',
                'parent': "职位管理",
                'platform_name': "中台",
                'description': "修改",
                'remark': "",
            },
            {
                'name': '添加',
                'parent': "职位管理",
                'platform_name': "中台",
                'description': "添加",
                'remark': "",
            },
            {
                'name': '删除',
                'parent': "职位管理",
                'platform_name': "中台",
                'description': "删除",
                'remark': "",
            },
            {
                'name': '部门管理',
                'parent': "权限管理",
                'platform_name': "中台",
                'description': "部门管理",
                'remark': "",
            },
            {
                'name': '查询',
                'parent': "部门管理",
                'platform_name': "中台",
                'description': "查询",
                'remark': "",
            },
            {
                'name': '修改',
                'parent': "部门管理",
                'platform_name': "中台",
                'description': "修改",
                'remark': "",
            },
            {
                'name': '添加',
                'parent': "部门管理",
                'platform_name': "中台",
                'description': "添加",
                'remark': "",
            },
            {
                'name': '删除',
                'parent': "部门管理",
                'platform_name': "中台",
                'description': "删除",
                'remark': "",
            },
            {
                'name': '员工列表',
                'parent': "权限管理",
                'platform_name': "中台",
                'description': "员工列表",
                'remark': "",
            },
            {
                'name': '查询',
                'parent': "员工列表",
                'platform_name': "中台",
                'description': "查询",
                'remark': "",
            },
            {
                'name': '修改',
                'parent': "员工列表",
                'platform_name': "中台",
                'description': "修改",
                'remark': "",
            },
            {
                'name': '添加',
                'parent': "员工列表",
                'platform_name': "中台",
                'description': "添加",
                'remark': "",
            },
            {
                'name': '删除',
                'parent': "员工列表",
                'platform_name': "中台",
                'description': "删除",
                'remark': "",
            },
        ]
