# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-14 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agent_customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCustomerSaleChance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('staff_id', models.IntegerField(verbose_name='所属机会员工id')),
                ('founder_id', models.IntegerField(verbose_name='创建机会员工id')),
                ('organization_id', models.IntegerField(verbose_name='组织id')),
                ('product_id', models.IntegerField(verbose_name='产品id')),
                ('education', models.CharField(choices=[('primary', '小学'), ('secondary', '初中'), ('technicalsecondary', '中专'), ('juniorcollege', '大专'), ('highschool', '高中'), ('undergraduate', '本科'), ('master', '硕士'), ('doctor', '博士'), ('other', '其他')], default='other', max_length=32, verbose_name='学历')),
                ('city', models.CharField(default='', max_length=128, verbose_name='地址')),
                ('end_time', models.DateField(max_length=20, verbose_name='机会截至时间')),
                ('batch_no', models.CharField(default='', max_length=128, verbose_name='批号')),
                ('source', models.CharField(choices=[('create', '创建'), ('assign', '分配'), ('sys', '系统分配'), ('other', '其他')], default='create', max_length=64, verbose_name='来源')),
                ('is_end', models.BooleanField(default=False, verbose_name='机会是否手动结束')),
                ('remark', models.TextField(default='', verbose_name='备注')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'agent_customer_salechance',
            },
        ),
        migrations.CreateModel(
            name='SaleChanceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=64, unique=True, verbose_name='唯一逻辑码')),
                ('order_id', models.IntegerField(verbose_name='订单id')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('sale_chance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent_customer.AgentCustomerSaleChance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='phone',
            field=models.CharField(default='', max_length=16, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='agentcustomer',
            name='customer_id',
            field=models.IntegerField(default=0, verbose_name='customer_id'),
        ),
        migrations.AddField(
            model_name='agentcustomersalechance',
            name='agent_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent_customer.AgentCustomer'),
        ),
    ]
