# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-14 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_customer', '0002_auto_20200814_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcustomersalechance',
            name='agent_id',
            field=models.IntegerField(default=0, verbose_name='代理商id'),
        ),
        migrations.AlterField(
            model_name='agentcustomersalechance',
            name='education',
            field=models.CharField(choices=[('primary', '小学'), ('middle', '初中'), ('middlecollege', '中专'), ('college', '大专'), ('hign', '高中'), ('undergraduate', '本科'), ('master', '硕士'), ('doctor', '博士'), ('other', '其他')], default='other', max_length=32, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='agentcustomersalechance',
            name='end_time',
            field=models.DateField(verbose_name='机会截至时间'),
        ),
    ]
