# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-14 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent_customer', '0003_auto_20200814_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentcustomersalechance',
            old_name='product_id',
            new_name='production_id',
        ),
    ]
