# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-14 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_customer', '0004_auto_20200814_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcustomer',
            name='person_id',
            field=models.IntegerField(default=0, verbose_name='customer_id'),
        ),
    ]
