# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-19 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_customer', '0005_agentcustomer_person_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentcustomersalechance',
            name='city',
        ),
        migrations.RemoveField(
            model_name='agentcustomersalechance',
            name='education',
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='city',
            field=models.CharField(default='', max_length=128, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='education',
            field=models.CharField(choices=[('primary', '小学'), ('middle', '初中'), ('middlecollege', '中专'), ('college', '大专'), ('hign', '高中'), ('undergraduate', '本科'), ('master', '硕士'), ('doctor', '博士'), ('other', '其他')], default='other', max_length=32, verbose_name='学历'),
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='name',
            field=models.CharField(default='', max_length=16, verbose_name='客户姓名'),
        ),
        migrations.AlterField(
            model_name='agentcustomer',
            name='person_id',
            field=models.IntegerField(default=0, verbose_name='person_id'),
        ),
    ]
