# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-08-19 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent_customer', '0006_auto_20200819_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentcustomer',
            name='customer_id',
        ),
    ]
