# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-09-16 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_customer', '0007_remove_agentcustomer_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcustomer',
            name='gender',
            field=models.CharField(choices=[('man', '男士'), ('woman', '女士'), ('unknown', '未知')], default='unknown', max_length=24, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='qq',
            field=models.CharField(default='', max_length=32, verbose_name='客户qq'),
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='source',
            field=models.CharField(default='', max_length=64, verbose_name='客户来源'),
        ),
        migrations.AddField(
            model_name='agentcustomer',
            name='wechat',
            field=models.CharField(default='', max_length=64, verbose_name='客户微信'),
        ),
        migrations.AddField(
            model_name='agentcustomersalechance',
            name='intention',
            field=models.CharField(choices=[('no', '无意向'), ('low', '低意向'), ('middle', '中意向'), ('high', '高意向'), ('unknown', '未知')], default='unknown', max_length=128, verbose_name='意向'),
        ),
    ]
